/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MerkleTree;

import java.util.ArrayList;
import java.util.List;
import java.util.stream.*;

public class App {
	public String getGreeting() {
		return "Hello world.";
	}

	public static void main(String[] args) {

		String test = "hello\nhow\nare\nyou\n???\nblabla\ntoto\nlast";

		List<byte[]> bytelist = new ArrayList<>();
		String[] strings = test.split("\n");
		for (String s : strings) {
			bytelist.add(s.getBytes());
		}
		MerkleTree treetest = new MerkleTree(bytelist);
		treetest.exportTreeViz("/home/mpostma/Documents/cours-a3/distributed_programming/tp/tp4/test.dot");
		System.out.println(treetest.getProof(6).stream().map((byte[] hash) -> Utils.encodeHexString(hash, 5))
				.collect(Collectors.toList()));
		// MerkleTree subtreetest = MerkleTree.build(subtest);
		// List<MerkleTree> proof = treetest.proof(subtreetest);
		// System.out.println(proof);

	}
}
